runtime: java17
instance_class: F2
env: standard
handlers:
  - url: /.*
    script: this field is required, but ignored

#entrypoint not needed; see jar packaging and main-class set with pom
#entrypoint: java -jar target/cartest-0.0.1-SNAPSHOT.jar